INSERT INTO public.leads_comerciales
(empresa, contacto, cargo, tipo_empresa, ciudad, comuna, region, pais, sitio_web, prioridad, origen, estado_verificacion, etapa, notas)
VALUES
('FoodGroup S.p.A.', NULL, NULL, 'Maquila', 'Santiago', 'San Bernardo', 'Metropolitana', 'Chile', 'foodgroup.cl', 'Alta', 'Sitio web corporativo', 'No verificado', 'Prospecto', 'Producción de alimentos en polvo y maquila. Planta en San Bernardo, foco claro en maquila alimentaria.'),
('Proexa S.A.', NULL, NULL, 'Maquila', 'Santiago', 'RM', 'Metropolitana', 'Chile', 'proexa.cl', 'Alta', 'Sitio web corporativo', 'No verificado', 'Prospecto', 'Maquila alimentaria, molienda, mezcla, extrusión, envasado. Muy buen fit para servicios industriales y maquila de alimentos.'),
('Novafoods', 'Benjamín Medina', 'Fundador', 'Maquila', 'Santiago', 'Macul', 'Metropolitana', 'Chile', 'novafoods.cl', 'Alta', 'Sitio web corporativo / fuente pública', 'Verificado públicamente', 'Prospecto', 'Alimentos en polvo, bebidas funcionales y maquilas. Empresa con foco claro en desarrollo y fabricación para terceros.'),
('Goth Alimentos', NULL, NULL, 'Maquila', 'Santiago', 'Colina', 'Metropolitana', 'Chile', 'gothalimentos.cl', 'Alta', 'Sitio web corporativo', 'No verificado', 'Prospecto', 'Snacks, cacao, instantáneos y maquila. Buen prospecto para maquila y desarrollo de productos.'),
('IPAL', NULL, NULL, 'Productor de alimentos', 'Santiago', 'Santiago', 'Metropolitana', 'Chile', 'ipal.cl', 'Media', 'Sitio web corporativo', 'No verificado', 'Prospecto', 'Producción de alimentos y cereales. Productor local, potencial apertura a negocios B2B.'),
('CPM Foods', NULL, NULL, 'Maquila', 'Santiago', 'Santiago', 'Metropolitana', 'Chile', 'cpmfoods.cl', 'Alta', 'Sitio web corporativo', 'No verificado', 'Prospecto', 'Desarrollo y producción de bebidas para terceros. Muy alineado a fabricación para terceros.'),
('ABC Pack', NULL, NULL, 'Co-packing', 'Santiago', 'Santiago', 'Metropolitana', 'Chile', 'abcpack.cl', 'Alta', 'Sitio web corporativo', 'No verificado', 'Prospecto', 'Co-packing, envasado, etiquetado y fulfillment. Prospecto atractivo para servicios de acondicionamiento y envasado.'),
('Caixas Pack', NULL, NULL, 'Co-packing', 'Santiago', 'Lo Espejo', 'Metropolitana', 'Chile', 'caixaspack.cl', 'Alta', 'Sitio web corporativo', 'No verificado', 'Prospecto', 'Co-packing, etiquetado y logística. Encaje directo para servicios de packaging y operación.'),
('Soprole', 'Sebastián Tagle', 'Gerente General', 'Productor de alimentos', 'Santiago', 'San Bernardo / Renca', 'Metropolitana', 'Chile', 'soprole.cl', 'Media', 'Memoria / sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Lácteos y alimentos elaborados. Gran productor con potencial vínculo B2B.'),
('Carozzi', 'Santiago Valdés Birrell', 'Gerente General / CEO', 'Productor de alimentos', 'Santiago', 'Nos, San Bernardo', 'Metropolitana', 'Chile', 'carozzicorp.com', 'Media', 'Memoria corporativa', 'Verificado públicamente', 'Prospecto', 'Elaboración de alimentos. Cuenta grande, aproximación más estratégica.'),
('Watt''s', 'Santiago Larraín Cruzat', 'Gerente General', 'Productor de alimentos', 'Santiago', 'RM', 'Metropolitana', 'Chile', 'watts.cl', 'Media', 'Gobierno corporativo', 'Verificado públicamente', 'Prospecto', 'Alimentos elaborados. Productor relevante para negocios corporativos.'),
('ICB', 'Sergio Rojas Nazal', 'Gerente General', 'Productor de alimentos', 'Santiago', 'Quilicura', 'Metropolitana', 'Chile', 'icb.cl', 'Media', 'Sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Producción y distribución de alimentos. Empresa relevante en consumo masivo y food business.'),
('ICB Food Service', 'Gustavo Braun', 'Gerente General', 'Food service', 'Santiago', 'Santiago', 'Metropolitana', 'Chile', 'icbfs.cl', 'Media', 'Sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Food service / abastecimiento gastronómico. Interesante si buscamos canal horeca o institucional.'),
('Ideal', 'Randall Quesada', 'Gerente General', 'Productor de alimentos', 'Santiago', 'Quilicura / Talagante', 'Metropolitana', 'Chile', 'ideal.cl', 'Media', 'Sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Panificación y pastelería industrial. Cuenta grande, requiere aproximación corporativa.'),
('BredenMaster', NULL, NULL, 'Productor de alimentos', 'Santiago', 'Pudahuel', 'Metropolitana', 'Chile', 'bredenmaster.com', 'Media', 'Sitio corporativo', 'No verificado', 'Prospecto', 'Panadería congelada y listo para hornear. Actor relevante en panadería industrial.'),
('CIAL Alimentos', 'Marcelo Alvarado Espinosa', 'Gerente General', 'Productor de alimentos', 'Santiago', 'Pudahuel', 'Metropolitana', 'Chile', 'cial.cl', 'Media', 'Sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Cecinas, hamburguesas, lácteos y otros alimentos. Buen objetivo corporativo en alimentos procesados.'),
('Ovosur Chile', 'Andrés Sabaj Aylwin', 'Gerente General de Ovosur Chile', 'Productor de alimentos', 'Santiago', 'Maipú', 'Metropolitana', 'Chile', 'ovosur.cl', 'Media', 'Sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Ovoproductos. Empresa especializada con potencial B2B industrial.'),
('Fruna', 'Lucas Muller', 'CEO', 'Productor de alimentos', 'Santiago', 'Maipú', 'Metropolitana', 'Chile', 'fruna.cl', 'Baja', 'Fuente pública secundaria', 'Parcialmente verificado', 'Prospecto', 'Confites, golosinas y abarrotes. Gran productor, pero menos claro el encaje inmediato.'),
('Nestlé Chile', 'Rodrigo Camacho', 'Presidente Ejecutivo', 'Productor de alimentos', 'Santiago', 'Macul', 'Metropolitana', 'Chile', 'nestle.cl', 'Baja', 'Sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Alimentos y bebidas. Cuenta muy grande, abordaje institucional.'),
('CCU', 'Patricio Jottar', 'Gerente General', 'Bebidas', 'Santiago', 'Las Condes', 'Metropolitana', 'Chile', 'ccu.cl', 'Baja', 'Sitio corporativo', 'Verificado públicamente', 'Prospecto', 'Bebidas y snacks / alimentos. Gran corporativo; oportunidad más compleja y estratégica.')
ON CONFLICT DO NOTHING;