// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cygjjvnammxmezttzbuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5Z2pqdm5hbW14bWV6dHR6YnVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1ODY3NTUsImV4cCI6MjA5MTE2Mjc1NX0.r68y-44aAY_967kk5F6A1oaGPj_V6IbDr8hTbeLu6vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});